### ISSUE TITLE
[parse] Extract Links

### ISSUE THREAD

**Issue by rufuspollock** [datopian/markdowndb#4]
I want to query for forward links and back links to files both markdown and non-markdown so that i can display back links, a network graph, deadlinks etc

- standard markdown links
- obsidian wiki links
- embeds of files e.g. `![...]`
  - wiki link embeds of files

So all of these

```md
[...](...)
![...](...)
[[...]]   # wiki link style including with title
[[...|my title]]   # wiki link style including with title
![[...]]  # for images and other embeds
```

## Acceptance

- [x] Support internal links (i.e. `../abc` or `/abc/` or `abc`
- [x] Supports all link types
	- [x] markdown
	- [x] wikilinks
	- [x] markdown embeds
	- [x] wikilink embeds

Bonus

- [ ] convenience query functions (or at least a tutorial on select functions to run)
- [x] ~~Support both with markdown file extension and without~~ **✅2023-11-17 ❌ does not make sense**

## Taks

- [x] first breaking test
- [x] code for link extraction from a markdown file (remark plugin or at least uses remark ast?)
- [x] table in database of links
- [x] query functions

## Design - new

Why do i want links?

- **Backlinks** List all files that link to this file
- **Network graph**: do a network graph
- **Pages that don't yet exist** (or deadlinks) Or list all files that are linked to but don't exist yet ...
- **Deadlinks** is this image used anywhere?

```
getNonExistentFiles
getAllFilesThatLinkTo(fileOrUrl)
```

## Design

Crudely: `[hello](world)` becomes ...

```typescript
// note we implicitly 
interface Link {
  from: "abc/foobar" // File path for the source file
  to: "abc/world.md" // points to the end of the link ( can be an external )  
  toRaw: 'world' // the raw link href
  text: 'hello'
  embed: true, // is it an embed link (default: false)
  internal: true // default true (external means http etc - not inside the contentbase) 
}
```

### Analysis

For each of the following markdown in document `abc/foobar.md` what is the output link object

```md
[hello](world)
```
=>
```javascript
{
  toRaw: 'world' // raw link to
  text: 'hello'
  embed: true, // is it an embed link (default: false)
  internal: true // default true (external means http etc - not inside the contentbase) 
  from: "abc/foobar" // File path for the source file
  to: "abc/world.md" // points to the end of the link ( can be an external )  
}
```
---
This markdown

```md
[hello](world.png)
```
=>
```javascript=
{
  toRaw: 'world.png' // raw link to
  text: 'hello'
  embed: true, // is it an embed link (default: false)
  internal: true // default true (external means http etc - not inside the contentbase) 
  from: "abc/foobar" // File path for the source file
  to: "abc/world.png" // points to the end of the link ( can be an external )  
}
```
---
This markdown
```md
[hello](world.mdx)
```
```javascript=
{
  toRaw: 'world.mdx' 
  text: 'hello',
  embed: true,
  internal: true, 
  from: "abc/foobar",
  to: "abc/world.mdx" 
}
```
---
This markdown
```md
[hello](/world)
```
=>
```javascript=
{
  toRaw: '/world', // raw link to
  text: 'hello',
  embed: true, 
  internal: true, 
  from: "abc/foobar",
  to: "abc/world"
}
```
---
This markdown
```
![hello](world.png)
```
=>
```javascript=
{
  toRaw: 'world.png', // raw link to
  text: 'hello',
  embed: true, 
  internal: true, 
  from: "abc/foobar",
  to: "abc/world.png"
}
```
---
```
![](world.png)
```
=>
```javascript=
{
  toRaw: 'world.png', // raw link to
  text: 'hello',
  embed: true, // is it an embed link (default: false)
  internal: true, // default true (external means http etc - not inside the contentbase)
  from: "abc/foobar", // File path for the source file
  to: "abc/world.png" // points to the end of the link ( can be an external )
}
```
---
Question:

- how do we reference another file? what is it's primary key
  - obvious answer is path ...
    - but path relative to what? (relative to the root of the tree ... )
      - but what is the root of the tree? ... we know that when parsing ...

**Comment by rufuspollock** [comment]
This doesn't seem to be working for me in a local test. @mohamedsalem401 can you comment on your experience too. We may need to reopen and fix.

**Comment by mohamedsalem401** [comment]
@olayway 

Links don't work between files when using my local machine.

For example, the following links in an md file don't add any links to the database, although the file markdown.md exists and is correctly added to the files table:
```
[page](markdowndb.md)
[page](markdowndb)
![page link](markdowndb)
```
One possible fix for the issue is in the markdown.db file on lines 121 and 122:
```
const destPath = resolveLinkToUrlPath(linkSrc, url);
const destFile = filesToInsert.find((file) => file.url_path === destPath);
if (!destFile) {
    return;
}
```
If we `console.log` the destPath (the path to the link) and url_path of all files:
```
files.url_path => [
  'data-cli',
  'datapipes',
  'flowershow',
  'giftless',
  'markdowndb',
  'portaljs'
]
destPath => ":\markdowndb"
```
You can see that, for some reason, the path for links in the file gets preceded by :\ I don't know if this is intentional to match one of our use cases. In this case, we may want to fix it for using our library with local files.

Let me know if I should just delete :\ in destPath or add :\ before url_paths or only add :\ in the comparison (i.e., `const destFile = filesToInsert.find((file) => ":\" + file.url_path === destPath);`).

**Comment by rufuspollock** [comment]
Reopening the issue as there is a bug atm.

**Comment by rufuspollock** [comment]
@mohamedsalem401

- [ ]  finish doing the analysis of the cases with the results in hackmd and then move above
- [ ] turn this into tests (can take over existing extractWikiLinks (and don't worry if we break existing system)
- [ ] get the tests passing by updating the code
- [ ] add a simple test (we don't need all the cases) on process.ts

NB: this is also a chance to look at how remark markdown parsing works ...

**Comment by mohamedsalem401** [comment]
When coding, I like to maintain high-level notes for consideration. I will leave them in a comment if that's acceptable.
1. **Default Extension for Paths:**
   If a path is presented as `[hello](world)`, should the system default the extension to `md`, `mdx`, or not?
2. **Handling Embedded External Links:**
   How should the system handle embedded external links, such as YouTube iframes or similar elements?
3. **Handling Paths Outside the Root Folder:**
   When a file (e.g., `abc/foobar`) contains a link like `[hello](../../world)`, what should the `to` attribute point to?
4. **Absolute vs. Relative Paths:**
   How do we want to handle absolute paths like `[hello](/world)` and `[hello](./world)`? Should the `to` attribute reflect the absolute path, or should it be relative to the root?
5. **Handling Link Text:**
   How should the system handle link text, e.g., should it be trimmed (e.g., `text: 'hello  '`)?
6. **Differentiating Internal and External Links:**
   How should we differentiate between internal and external links? Should we rely on a specific prefix (e.g., `/` for internal and `https` for external), or is there another preferred method?

---
Advanced Considerations (these were on the back of my mind and should definitely be ignored for now):
7. **Links to Sections or Headings:**
   How should the system handle links to specific sections or headings within a document?
8. **Handling Links to Directories:**
   How should the system handle links that point to directories rather than individual files? Should it default to pointing to `index.md`?
9. **Supporting Link Titles for Accessibility:**
   Should the system support link titles for improved accessibility, e.g., `[hello](./world 'TITLE')`?
10. **Handling URLs and Email Addresses:**
    How should the system handle URLs and email addresses enclosed in angle brackets, e.g., `<email@gmail.com>`?
11. **Linking Images in Markdown:**
    How would you like the system to handle linking images in Markdown, considering the special syntax for adding links to images?

**Comment by rufuspollock** [comment]
Great set of questions.

> When coding, I like to maintain high-level notes for consideration. I will leave them in a comment if that's acceptable.
> 
> 1. **Default Extension for Paths:**
>    If a path is presented as `[hello](world)`, should the system default the extension to `md`, `mdx`, or not?

That isn't a valid link so this situation should never happen.

> 2. **Handling Embedded External Links:**
>    How should the system handle embedded external links, such as YouTube iframes or similar elements?

Ignore them. Only stuff like `![](youtube link)`

> 3. **Handling Paths Outside the Root Folder:**
>    When a file (e.g., `abc/foobar`) contains a link like `[hello](../../world)`, what should the `to` attribute point to?

Allow it for now. It's just a broken link. Bonus would be logging a warning.

> 4. **Absolute vs. Relative Paths:**
>    How do we want to handle absolute paths like `[hello](/world)` and `[hello](./world)`? Should the `to` attribute reflect the absolute path, or should it be relative to the root?

`./world` is easy in that it is the same as world and `/world` should default to the root of the content system.

> 5. **Handling Link Text:**
>    How should the system handle link text, e.g., should it be trimmed (e.g., `text: 'hello  '`)?

Don't trim the text.

> 6. **Differentiating Internal and External Links:**
>    How should we differentiate between internal and external links? Should we rely on a specific prefix (e.g., `/` for internal and `https` for external), or is there another preferred method?

External links have a scheme e.g. `http, https, ftp`.

> Advanced Considerations (these were on the back of my mind and should definitely be ignored for now):
> 7. Links to Sections or Headings:
> How should the system handle links to specific sections or headings within a document?

This is a great one and i think we need to have a fragment field and extract the `fragment` attribute on links.

> 8. Handling Links to Directories:
> How should the system handle links that point to directories rather than individual files? Should it default to pointing to index.md?

Just point to the directory as it would be like a file e.g. if i have [the profiles section](/profiles/) just have to be `to: "profiles/"`

> 9. Supporting Link Titles for Accessibility:
> Should the system support link titles for improved accessibility, e.g., [hello](./world 'TITLE')?

Not for now.

> 10. Handling URLs and Email Addresses:
> How should the system handle URLs and email addresses enclosed in angle brackets, e.g., <email@gmail.com>?

ignore them

> 11. Linking Images in Markdown:
> How would you like the system to handle linking images in Markdown, considering the special syntax for adding links to images?

I'm not sure i get this one ...

**Comment by rufuspollock** [comment]
@mohamedsalem401 can we now close this?

**Comment by mohamedsalem401** [comment]
> `./world` is easy in that it is the same as world and `/world` should default to the root of the content system

This needs a simple change in the code to be addressed.

**Comment by rufuspollock** [comment]
@mohamedsalem401 to summarize:

- What do we want to use the link database for? Basically to find back links etc
- We want `[[xxx]` to work and we can default to this being a `.md` extension
- What does obsidian dataview do?

**Comment by rufuspollock** [comment]
> > `./world` is easy in that it is the same as world and `/world` should default to the root of the content system
> 
> This needs a simple change in the code to be addressed.

Did we make this change? If not let's open an inbox issue for Link improvements and put this in there so we don't forget it.
